worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

rtmp {
  server {
    listen 1935;
    chunk_size 4096;

    application live {
      live on;
      record off;
      hls on;
      hls_path /tmp/hls;
      hls_fragment 2s;
      hls_playlist_length 10s;
    }
  }
}

http {
  sendfile on;
  types {
    application/vnd.apple.mpegurl m3u8;
    video/mp2t ts;
  }
  default_type application/octet-stream;

  server {
    listen 80;

    location / {
      root /tmp/hls;
      add_header Cache-Control no-cache;
      add_header Access-Control-Allow-Origin *;
    }

    location /health {
      return 200 'ok';
      add_header Content-Type text/plain;
    }
  }
}
